name: Setup dependencies
description: Setup depdendencies for Libry-Content

inputs:
  install-dependencies:
    description: 'Install dependencies'
    required: false
    default: 'true'
  node-version:
    description: 'NodeJS version'
    required: false
    default: '14'
  npm-version:
    description: 'NPM version'
    required: false
    default: '7'
  cache-name:
    description: 'Cache name'
    required: false
    default: 'cache-node-modules-v3'
  github-token:
    description: GitHub Token, used to find the PR associated with the commit.
    required: false
    default: ''
outputs:
  pull-request:
    description: "Associated GitHub Pull Request as a JSON string"
    value: ${{ steps.pr.outputs.pr }}
  pull-request-number:
    description: "Numerical identifier of associated GitHub Pull Request"
    value: ${{ steps.pr.outputs.number }}
runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v2
    - if: inputs.install-dependencies == 'true'
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
    - if: inputs.install-dependencies == 'true'
      run: npm install -g npm@${{ inputs.npm-version }}
      shell: bash
    - if: inputs.install-dependencies == 'true'
      id: cache-node-modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules-v3
      with:
        path: |
          ~/node_modules
          ~/**/node_modules
        key: ${{ runner.os }}-build-${{ inputs.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ inputs.cache-name }}-
    - if: inputs.install-dependencies == 'true' && steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci && npm run postinstall
      shell: bash
    - uses: rlespinasse/github-slug-action@4.0.0
    - run: |
        echo "E2E_DATASET=$(echo "e2e-${{ env.GITHUB_REF_SLUG }}" | head -c 20)" >> $GITHUB_ENV
        echo "PREVIEW_DEPLOYMENT_URL=${{ env.GITHUB_REF_SLUG }}.qa.bibliotek-test.io" >> $GITHUB_ENV
      shell: bash
    - name: "Get PR associated with sha ${{ github.event.pull_request.head.sha || github.sha }}"
      if: inputs.github-token != ''
      uses: 8BitJonny/gh-get-current-pr@1.3.0
      id: pr
      with:
        github-token: ${{ inputs.github-token }}
        sha: ${{ github.event.pull_request.head.sha || github.sha }}
        filterOutClosed: true
    - name: Export Pull Request number and Jira Issue as environment variables
      if: inputs.github-token != '' && steps.pr.outputs.pr_title != ''
      run: |
        echo "JIRA_ISSUE=$(echo "${{ steps.pr.outputs.pr_title }}" | grep -e '[A-Z]\+-[0-9]\+' -o)" >> $GITHUB_ENV
        echo "PR_NUMBER=$(echo "${{ steps.pr.outputs.number }}")" >> $GITHUB_ENV
      shell: bash
    - name: Show warning if no PR found
      if: inputs.github-token != '' && steps.pr.outputs.pr_title == ''
      run: |
        echo "No pull request found for ${{ github.event.pull_request.head.sha || github.sha }}"
      shell: bash

    # Retry once if no PR was found
    -
      if: inputs.github-token != '' && steps.pr.outputs.pr_title == ''
      run: echo "Retrying in 60 secs..." && sleep 60
      shell: bash
    -
      if: inputs.github-token != '' && steps.pr.outputs.pr_title == ''
      uses: 8BitJonny/gh-get-current-pr@1.3.0
      id: pr2
      with:
        github-token: ${{ inputs.github-token }}
        sha: ${{ github.event.pull_request.head.sha || github.sha }}
        filterOutClosed: true
    -
      if: inputs.github-token != '' && steps.pr.outputs.pr_title == ''
      run: |
        echo "JIRA_ISSUE=$(echo "${{ steps.pr2.outputs.pr_title }}" | grep -e '[A-Z]\+-[0-9]\+' -o)" >> $GITHUB_ENV
        echo "PR_NUMBER=$(echo "${{ steps.pr2.outputs.number }}")" >> $GITHUB_ENV
      shell: bash
    -
      if: inputs.github-token != '' && steps.pr.outputs.pr_title == '' && steps.pr2.outputs.pr_title == ''
      run: |
        echo "No pull request found for ${{ github.event.pull_request.head.sha || github.sha }}"
      shell: bash
