name: Notify failure
description: Send a message to Microsoft Teams on failure

inputs:
  ms-teams-webhook-uri:
    description: "Incoming webhook URI to Microsoft Teams"
    required: true
  error-message:
    description: "Message indicating the cause of failure"
    required: true
runs:
  using: "composite"

  steps:
    - name: DEBUG
      shell: bash
      run: |
        echo "DEBUG"
        echo "---------------------"
        echo "${{ inputs.error-message }}"
        echo "---------------------"
        pwd
        echo "---------------------"
        ls
    - name: Send a message to Microsoft Teams on failure
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ inputs.ms-teams-webhook-uri }}
        text: >
          ⚠️ ${{ inputs.error-message }}
