name: Notify Teams on failure
description: Notify Teams channel on job failure

inputs:
  title:
    description: "Card title"
    required: true
  text:
    description: "Card text"
    required: true
  webhooks-url:
    description: "Webhooks URL"
    required: true
runs:
  using: node16
  main: notify-teams.mjs
