name: Notify Teams on failure
description: Notify Teams channel on job failure

inputs:
  title:
    description: "Card title"
    required: true
  text:
    description: "Card text"
    required: true
  webhooks-url:
    description: "Webhooks URL"
    required: true
runs:
  using: "composite"
  steps:
    # Ref: https://github.com/orgs/community/discussions/32169
    - uses: actions/github-script@v6
      id: job-url
      with:
        script: |
          const { data } = await github.rest.actions.listJobsForWorkflowRunAttempt({
            ...context.repo,
            run_id: context.runId,
            attempt_number: process.env.GITHUB_RUN_ATTEMPT,
          });
          const job = data.jobs[0];
          console.log(job)

          const https = require("node:https");

          console.log("Hello world");
          await new Promise((resolve, reject) => {
            https.get({
              hostname: 'bibliografisk.bs.no',
              path: '/v1/publications',
            }, (res) => {
              console.log(res.statusCode);
              resolve();
            })
          });

          return job?.html_url
        result-encoding: string
    # MessageCard reference: https://learn.microsoft.com/nb-no/outlook/actionable-messages/message-card-reference
    # - name: Notify Teams on failure
    #   if: failure()
    #   shell: bash
    #   run: >
    #     curl -s -X POST ${{ inputs.webhooks-url }}
    #     -H 'Content-Type: application/json; charset=utf-8' 
    #     -d '{
    #       "@type": "MessageCard",
    #       "@context": "https://schema.org/extensions",
    #       "title": "${{ inputs.title }}",
    #       "text":  "${{ inputs.text }}",
    #       "potentialAction": [
    #         { "@type": "OpenUri", "name": "Vis logg", "targets": [{ "os": "default", "uri": "${{ steps.job-url.outputs.result }}" }] }
    #       ]
    #     "}'
