name: Notify Teams
description: Notify Teams channel
inputs:
  webhooks-url:
    description: 'Power Automate flow URL that we should post the card to'
    required: true
  title:
    description: 'Card title. Can contain Markdown'
    required: true
  titleColor:
    description: 'Optional title text color. Values: "default", "dark", "light", "accent", "good", "warning", "attention"'
    required: false
  text:
    description: 'Card text. Can contain Markdown'
    required: true
  textColor:
    description: 'Optional text color. Values: "default", "dark", "light", "accent", "good", "warning", "attention"'
    required: false
  icon:
    description: '(Optional) URL to icon or base64 encoded image string'
    required: false
runs:
  using: node20
  main: ./dist/index.mjs
