name: Notify Teams
description: Notify Teams channel and include a link to the current GitHub Actions job
inputs:
  title:
    description: "Card title"
    required: true
  text:
    description: "Card text"
    required: true
  webhooks-url:
    description: "Webhooks URL"
    required: true
  github-token:
    description: "GitHub token"
    required: true
runs:
  using: node20
  main: ./dist/index.mjs
