name: Setup node
description: Setup Node and NPM, then optionally install and cache NPM dependencies.

inputs:
  node-version:
    description: "NodeJS version"
    required: false
    default: "16"
  npm-version:
    description: "NPM version"
    required: false
  install-dependencies:
    description: "Whether to install dependencies"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
    - if: inputs.npm-version
      run: npm install -g npm@${{ inputs.npm-version }}
      shell: bash
    - if: inputs.install-dependencies == 'true' && steps.setup-node.outputs.cache-hit != 'true'
      run: |
        npm ci
        npm run postinstall --if-present
      shell: bash
