name: Setup node
description: Setup Node and NPM, then optionally install and cache NPM dependencies.

inputs:
  node-version:
    description: "NodeJS version"
    required: false
    default: "18"
  npm-version:
    description: "NPM version"
    required: false
  gc-artifact-registry-credentials:
    description: "JSON credentials used to authenticate in Google Cloud package registry"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - if: inputs.npm-version
      run: npm install -g npm@${{ inputs.npm-version }}
      shell: bash
    - id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/node_modules
          ~/**/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
    - if: inputs.gc-artifact-registry-credentials
      run: |
        # echo "${{ inputs.gc-artifact-registry-credentials }}" > google_key.json
        # export GOOGLE_APPLICATION_CREDENTIALS=google_key.json
        export GOOGLE_APPLICATION_CREDENTIALS="${{ inputs.gc-artifact-registry-credentials }}"
        npx google-artifactregistry-auth
      shell: bash
    - run: |
        # Make sure we don't install and create cache yet
        exit 1
      shell: bash
    - if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        npm ci
        npm run postinstall --if-present
      shell: bash
