name: Setup node
description: Setup Node and NPM, then optionally install and cache NPM dependencies.

inputs:
  node-version:
    description: "NodeJS version"
    required: false
    default: "14"
  npm-version:
    description: "NPM version"
    required: false
    default: "8"
  install-dependencies:
    description: "Whether to install dependencies"
    required: false
    default: "true"
  cache-dependencies:
    description: "Whether to cache dependencies"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
    - run: npm install -g npm@${{ inputs.npm-version }}
      shell: bash
    - id: cache-dependencies
      if: inputs.install-dependencies == 'true' && inputs.cache-dependencies == 'true'
      uses: actions/cache@v2
      with:
        path: |
          ~/node_modules
          ~/**/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
    - if: inputs.install-dependencies == 'true' && (inputs.cache-dependencies != 'true' || steps.cache-dependencies.outputs.cache-hit != 'true')
      run: |
        npm ci
        npm run postinstall --if-present
      shell: bash
