name: Get pull request with branch
description: Get pull request associated with branch for Libry-Content

inputs:
  github-token:
    description: GitHub Token, used to find the PR associated with the commit.
    required: true
    default: ""
  filter-out-closed:
    description: Whether to ignore closed pull requests
    required: false
    default: true
outputs:
  pull-request:
    description: "Associated GitHub Pull Request as a JSON string"
    value: ${{ steps.pr.outputs.pr }}
  pull-request-number:
    description: "Numerical identifier of associated GitHub Pull Request"
    value: ${{ steps.pr.outputs.number }}
runs:
  using: "composite"

  steps:
    - uses: rlespinasse/github-slug-action@4.0.0
    - name: "Get PR associated with sha ${{ github.event.pull_request.head.sha || github.sha }}"
      uses: 8BitJonny/gh-get-current-pr@1.3.0
      id: pr
      with:
        github-token: ${{ inputs.github-token }}
        sha: ${{ github.event.pull_request.head.sha || github.sha }}
        filterOutClosed: ${{ inputs.filter-out-closed }}
    - run: |
        echo "PR_NUMBER=${{ github.event.pull_request.number || steps.pr.outputs.number }}" >> $GITHUB_ENV
        echo "PR_BRANCH=${{ env.GITHUB_HEAD_REF }}" >> $GITHUB_ENV
        echo "PR_BRANCH_SLUG=${{ env.GITHUB_HEAD_REF_SLUG }}" >> $GITHUB_ENV
        echo "PR_DEPLOYMENT_URL=pr-${{ github.event.pull_request.number || steps.pr.outputs.number }}.qa.bibliotek-test.io" >> $GITHUB_ENV
        echo "E2E_DATASET=e2e-${{ github.event.pull_request.number || steps.pr.outputs.number }}" >> $GITHUB_ENV
        echo "JIRA_ISSUE=$(echo "${{ github.event.pull_request.title || steps.pr.outputs.pr_title }}" | grep -e '[A-Z]\+-[0-9]\+' -o)" >> $GITHUB_ENV
      shell: bash
