name: Get pull request with branch
description: Get pull request associated with branch for Libry-Content

inputs:
  github-token:
    description: GitHub Token, used to find the PR associated with the commit.
    required: true
    default: ""
  filter-out-closed:
    description: "Whether to ignore closed pull requests. If the commit is not present in the default branch, closed pull requests cannot be found."
    required: false
    default: 'true'
outputs:
  json:
    description: "Associated GitHub Pull Request as a JSON string"
    value: ${{ steps.pr.outputs.pr }}
  number:
    description: "Numerical identifier of associated GitHub Pull Request"
    value: ${{ steps.pr.outputs.number }}
  title:
    description: "Title of associated GitHub Pull Request"
    value: ${{ steps.pr.outputs.pr_title }}
  url:
    description: "URL of associated GitHub Pull Request"
    value: ${{ steps.pr.outputs.pr_url }}

runs:
  using: "composite"

  steps:
    - uses: rlespinasse/github-slug-action@4.0.0

    # Find the merged pull request that introduced the commit or open pull requests associated with the commit.
    # Ref: https://docs.github.com/en/rest/reference/commits#list-pull-requests-associated-with-a-commit
    - name: "Get PR associated with sha ${{ github.event.pull_request.head.sha || github.sha }}"
      uses: 8BitJonny/gh-get-current-pr@1.3.0
      id: pr
      with:
        github-token: ${{ inputs.github-token }}
        sha: ${{ github.event.pull_request.head.sha || github.sha }}
        filterOutClosed: ${{ inputs.filter-out-closed }}

    - run: |
        echo "PR_NUMBER=${{ steps.pr.outputs.number }}" >> $GITHUB_ENV
      shell: bash

    - name: Show warning if no PR found
      if: steps.pr.outputs.pr_title == ''
      run: |
        echo "No pull request found for ${{ github.event.pull_request.head.sha || github.sha }}"
      shell: bash
